// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/projects/[project].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/projects/[project].tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
